{"Timestamp":"2020-03-16T18:00:16.2110640-03:00","Level":"Information","MessageTemplate":"Starting web host"}
{"Timestamp":"2020-03-16T18:00:17.2696523-03:00","Level":"Debug","MessageTemplate":"Attempting to connect to TCP endpoint {host} after delay of {delay} seconds","Properties":{"host":"tls://localhost:5600/","delay":1}}
{"Timestamp":"2020-03-16T18:00:21.2852463-03:00","Level":"Error","MessageTemplate":"failure inside TCP socket: {message} - socket error found {socketErrorCode}","Exception":"System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_1(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.TcpSocketWriter.<>c__DisplayClass9_0.<<-ctor>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.ExponentialBackoffTcpReconnectionPolicy.ConnectAsync(Func`2 connect, Uri host, CancellationToken cancellationToken)","Properties":{"message":"No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600","socketErrorCode":"ConnectionRefused"}}
{"Timestamp":"2020-03-16T18:06:45.6953821-03:00","Level":"Information","MessageTemplate":"Starting web host"}
{"Timestamp":"2020-03-16T18:06:46.5501732-03:00","Level":"Debug","MessageTemplate":"Attempting to connect to TCP endpoint {host} after delay of {delay} seconds","Properties":{"host":"tls://localhost:5600/","delay":1}}
{"Timestamp":"2020-03-16T18:06:50.5766575-03:00","Level":"Error","MessageTemplate":"failure inside TCP socket: {message} - socket error found {socketErrorCode}","Exception":"System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_1(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.TcpSocketWriter.<>c__DisplayClass9_0.<<-ctor>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.ExponentialBackoffTcpReconnectionPolicy.ConnectAsync(Func`2 connect, Uri host, CancellationToken cancellationToken)","Properties":{"message":"No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600","socketErrorCode":"ConnectionRefused"}}
{"Timestamp":"2020-03-17T09:39:46.2100045-03:00","Level":"Information","MessageTemplate":"Starting web host"}
{"Timestamp":"2020-03-17T09:39:47.7401308-03:00","Level":"Debug","MessageTemplate":"Attempting to connect to TCP endpoint {host} after delay of {delay} seconds","Properties":{"host":"tls://localhost:5600/","delay":1}}
{"Timestamp":"2020-03-17T09:39:51.7732815-03:00","Level":"Error","MessageTemplate":"failure inside TCP socket: {message} - socket error found {socketErrorCode}","Exception":"System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_1(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.TcpSocketWriter.<>c__DisplayClass9_0.<<-ctor>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.ExponentialBackoffTcpReconnectionPolicy.ConnectAsync(Func`2 connect, Uri host, CancellationToken cancellationToken)","Properties":{"message":"No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600","socketErrorCode":"ConnectionRefused"}}
{"Timestamp":"2020-03-17T09:43:46.4162751-03:00","Level":"Information","MessageTemplate":"Starting web host"}
{"Timestamp":"2020-03-17T09:43:47.4980679-03:00","Level":"Debug","MessageTemplate":"Attempting to connect to TCP endpoint {host} after delay of {delay} seconds","Properties":{"host":"tls://localhost:5600/","delay":1}}
{"Timestamp":"2020-03-17T09:43:51.5137980-03:00","Level":"Error","MessageTemplate":"failure inside TCP socket: {message} - socket error found {socketErrorCode}","Exception":"System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_1(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.TcpSocketWriter.<>c__DisplayClass9_0.<<-ctor>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.ExponentialBackoffTcpReconnectionPolicy.ConnectAsync(Func`2 connect, Uri host, CancellationToken cancellationToken)","Properties":{"message":"No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600","socketErrorCode":"ConnectionRefused"}}
{"Timestamp":"2020-03-17T09:45:40.6023004-03:00","Level":"Information","MessageTemplate":"Starting web host"}
{"Timestamp":"2020-03-17T09:45:41.4090448-03:00","Level":"Debug","MessageTemplate":"Attempting to connect to TCP endpoint {host} after delay of {delay} seconds","Properties":{"host":"tls://localhost:5600/","delay":1}}
{"Timestamp":"2020-03-17T09:45:45.4335076-03:00","Level":"Error","MessageTemplate":"failure inside TCP socket: {message} - socket error found {socketErrorCode}","Exception":"System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_1(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.TcpSocketWriter.<>c__DisplayClass9_0.<<-ctor>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.ExponentialBackoffTcpReconnectionPolicy.ConnectAsync(Func`2 connect, Uri host, CancellationToken cancellationToken)","Properties":{"message":"No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600","socketErrorCode":"ConnectionRefused"}}
{"Timestamp":"2020-03-17T10:45:24.4628937-03:00","Level":"Information","MessageTemplate":"Starting web host"}
{"Timestamp":"2020-03-17T10:45:25.9889472-03:00","Level":"Debug","MessageTemplate":"Attempting to connect to TCP endpoint {host} after delay of {delay} seconds","Properties":{"host":"tls://localhost:5600/","delay":1}}
{"Timestamp":"2020-03-17T10:45:30.0039992-03:00","Level":"Error","MessageTemplate":"failure inside TCP socket: {message} - socket error found {socketErrorCode}","Exception":"System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_1(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.TcpSocketWriter.<>c__DisplayClass9_0.<<-ctor>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.ExponentialBackoffTcpReconnectionPolicy.ConnectAsync(Func`2 connect, Uri host, CancellationToken cancellationToken)","Properties":{"message":"No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600","socketErrorCode":"ConnectionRefused"}}
{"Timestamp":"2020-03-17T10:45:55.9409635-03:00","Level":"Information","MessageTemplate":"Starting web host"}
{"Timestamp":"2020-03-17T10:45:57.0038881-03:00","Level":"Debug","MessageTemplate":"Attempting to connect to TCP endpoint {host} after delay of {delay} seconds","Properties":{"host":"tls://localhost:5600/","delay":1}}
{"Timestamp":"2020-03-17T10:46:01.0265231-03:00","Level":"Error","MessageTemplate":"failure inside TCP socket: {message} - socket error found {socketErrorCode}","Exception":"System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_1(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.TcpSocketWriter.<>c__DisplayClass9_0.<<-ctor>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.ExponentialBackoffTcpReconnectionPolicy.ConnectAsync(Func`2 connect, Uri host, CancellationToken cancellationToken)","Properties":{"message":"No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600","socketErrorCode":"ConnectionRefused"}}
{"Timestamp":"2020-03-17T10:46:39.2598769-03:00","Level":"Information","MessageTemplate":"Starting web host"}
{"Timestamp":"2020-03-17T10:46:40.3813383-03:00","Level":"Debug","MessageTemplate":"Attempting to connect to TCP endpoint {host} after delay of {delay} seconds","Properties":{"host":"tls://localhost:5600/","delay":1}}
{"Timestamp":"2020-03-17T10:46:44.4070564-03:00","Level":"Error","MessageTemplate":"failure inside TCP socket: {message} - socket error found {socketErrorCode}","Exception":"System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_1(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.TcpSocketWriter.<>c__DisplayClass9_0.<<-ctor>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.ExponentialBackoffTcpReconnectionPolicy.ConnectAsync(Func`2 connect, Uri host, CancellationToken cancellationToken)","Properties":{"message":"No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600","socketErrorCode":"ConnectionRefused"}}
{"Timestamp":"2020-03-17T14:12:25.4531973-03:00","Level":"Information","MessageTemplate":"Starting web host"}
{"Timestamp":"2020-03-17T14:12:26.4162679-03:00","Level":"Debug","MessageTemplate":"Attempting to connect to TCP endpoint {host} after delay of {delay} seconds","Properties":{"host":"tls://localhost:5600/","delay":1}}
{"Timestamp":"2020-03-17T14:12:30.4437081-03:00","Level":"Error","MessageTemplate":"failure inside TCP socket: {message} - socket error found {socketErrorCode}","Exception":"System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_1(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.TcpSocketWriter.<>c__DisplayClass9_0.<<-ctor>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.ExponentialBackoffTcpReconnectionPolicy.ConnectAsync(Func`2 connect, Uri host, CancellationToken cancellationToken)","Properties":{"message":"No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600","socketErrorCode":"ConnectionRefused"}}
{"Timestamp":"2020-03-17T14:21:32.8516219-03:00","Level":"Information","MessageTemplate":"Starting web host"}
{"Timestamp":"2020-03-17T14:21:33.8115461-03:00","Level":"Debug","MessageTemplate":"Attempting to connect to TCP endpoint {host} after delay of {delay} seconds","Properties":{"host":"tls://localhost:5600/","delay":1}}
{"Timestamp":"2020-03-17T14:21:37.8283231-03:00","Level":"Error","MessageTemplate":"failure inside TCP socket: {message} - socket error found {socketErrorCode}","Exception":"System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_1(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.TcpSocketWriter.<>c__DisplayClass9_0.<<-ctor>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.ExponentialBackoffTcpReconnectionPolicy.ConnectAsync(Func`2 connect, Uri host, CancellationToken cancellationToken)","Properties":{"message":"No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600","socketErrorCode":"ConnectionRefused"}}
{"Timestamp":"2020-03-17T14:21:59.1207616-03:00","Level":"Information","MessageTemplate":"Starting web host"}
{"Timestamp":"2020-03-17T14:22:00.0829772-03:00","Level":"Debug","MessageTemplate":"Attempting to connect to TCP endpoint {host} after delay of {delay} seconds","Properties":{"host":"tls://localhost:5600/","delay":1}}
{"Timestamp":"2020-03-17T14:22:04.0990850-03:00","Level":"Error","MessageTemplate":"failure inside TCP socket: {message} - socket error found {socketErrorCode}","Exception":"System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_1(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.TcpSocketWriter.<>c__DisplayClass9_0.<<-ctor>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.ExponentialBackoffTcpReconnectionPolicy.ConnectAsync(Func`2 connect, Uri host, CancellationToken cancellationToken)","Properties":{"message":"No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600","socketErrorCode":"ConnectionRefused"}}
{"Timestamp":"2020-03-17T14:26:23.6494756-03:00","Level":"Information","MessageTemplate":"Starting web host"}
{"Timestamp":"2020-03-17T14:26:24.6694767-03:00","Level":"Debug","MessageTemplate":"Attempting to connect to TCP endpoint {host} after delay of {delay} seconds","Properties":{"host":"tls://localhost:5600/","delay":1}}
{"Timestamp":"2020-03-17T14:26:28.6879534-03:00","Level":"Error","MessageTemplate":"failure inside TCP socket: {message} - socket error found {socketErrorCode}","Exception":"System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_1(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.TcpSocketWriter.<>c__DisplayClass9_0.<<-ctor>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.ExponentialBackoffTcpReconnectionPolicy.ConnectAsync(Func`2 connect, Uri host, CancellationToken cancellationToken)","Properties":{"message":"No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600","socketErrorCode":"ConnectionRefused"}}
{"Timestamp":"2020-03-17T14:29:09.2098769-03:00","Level":"Information","MessageTemplate":"Starting web host"}
{"Timestamp":"2020-03-17T14:29:10.4065988-03:00","Level":"Debug","MessageTemplate":"Attempting to connect to TCP endpoint {host} after delay of {delay} seconds","Properties":{"host":"tls://localhost:5600/","delay":1}}
{"Timestamp":"2020-03-17T14:29:14.4311956-03:00","Level":"Error","MessageTemplate":"failure inside TCP socket: {message} - socket error found {socketErrorCode}","Exception":"System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_1(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.TcpSocketWriter.<>c__DisplayClass9_0.<<-ctor>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.ExponentialBackoffTcpReconnectionPolicy.ConnectAsync(Func`2 connect, Uri host, CancellationToken cancellationToken)","Properties":{"message":"No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600","socketErrorCode":"ConnectionRefused"}}
{"Timestamp":"2020-03-17T14:36:48.0252543-03:00","Level":"Information","MessageTemplate":"Starting web host"}
{"Timestamp":"2020-03-17T14:36:49.1471647-03:00","Level":"Debug","MessageTemplate":"Attempting to connect to TCP endpoint {host} after delay of {delay} seconds","Properties":{"host":"tls://localhost:5600/","delay":1}}
{"Timestamp":"2020-03-17T14:36:53.1680898-03:00","Level":"Error","MessageTemplate":"failure inside TCP socket: {message} - socket error found {socketErrorCode}","Exception":"System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_1(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.TcpSocketWriter.<>c__DisplayClass9_0.<<-ctor>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.ExponentialBackoffTcpReconnectionPolicy.ConnectAsync(Func`2 connect, Uri host, CancellationToken cancellationToken)","Properties":{"message":"No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600","socketErrorCode":"ConnectionRefused"}}
{"Timestamp":"2020-03-17T14:41:52.4116903-03:00","Level":"Information","MessageTemplate":"Starting web host"}
{"Timestamp":"2020-03-17T14:41:53.4263415-03:00","Level":"Debug","MessageTemplate":"Attempting to connect to TCP endpoint {host} after delay of {delay} seconds","Properties":{"host":"tls://localhost:5600/","delay":1}}
{"Timestamp":"2020-03-17T14:41:57.4398147-03:00","Level":"Error","MessageTemplate":"failure inside TCP socket: {message} - socket error found {socketErrorCode}","Exception":"System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_1(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.TcpSocketWriter.<>c__DisplayClass9_0.<<-ctor>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.ExponentialBackoffTcpReconnectionPolicy.ConnectAsync(Func`2 connect, Uri host, CancellationToken cancellationToken)","Properties":{"message":"No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600","socketErrorCode":"ConnectionRefused"}}
{"Timestamp":"2020-03-17T14:59:05.5110408-03:00","Level":"Information","MessageTemplate":"Starting web host"}
{"Timestamp":"2020-03-17T14:59:06.5055972-03:00","Level":"Debug","MessageTemplate":"Attempting to connect to TCP endpoint {host} after delay of {delay} seconds","Properties":{"host":"tls://localhost:5600/","delay":1}}
{"Timestamp":"2020-03-17T14:59:10.5225163-03:00","Level":"Error","MessageTemplate":"failure inside TCP socket: {message} - socket error found {socketErrorCode}","Exception":"System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_1(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.TcpSocketWriter.<>c__DisplayClass9_0.<<-ctor>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.ExponentialBackoffTcpReconnectionPolicy.ConnectAsync(Func`2 connect, Uri host, CancellationToken cancellationToken)","Properties":{"message":"No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600","socketErrorCode":"ConnectionRefused"}}
{"Timestamp":"2020-03-17T14:59:58.4296461-03:00","Level":"Information","MessageTemplate":"Starting web host"}
{"Timestamp":"2020-03-17T14:59:59.4385970-03:00","Level":"Debug","MessageTemplate":"Attempting to connect to TCP endpoint {host} after delay of {delay} seconds","Properties":{"host":"tls://localhost:5600/","delay":1}}
{"Timestamp":"2020-03-17T15:00:03.4588851-03:00","Level":"Error","MessageTemplate":"failure inside TCP socket: {message} - socket error found {socketErrorCode}","Exception":"System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_1(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.TcpSocketWriter.<>c__DisplayClass9_0.<<-ctor>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.ExponentialBackoffTcpReconnectionPolicy.ConnectAsync(Func`2 connect, Uri host, CancellationToken cancellationToken)","Properties":{"message":"No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600","socketErrorCode":"ConnectionRefused"}}
{"Timestamp":"2020-03-17T15:13:58.2767445-03:00","Level":"Information","MessageTemplate":"Starting web host"}
{"Timestamp":"2020-03-17T15:13:59.5624552-03:00","Level":"Debug","MessageTemplate":"Attempting to connect to TCP endpoint {host} after delay of {delay} seconds","Properties":{"host":"tls://localhost:5600/","delay":1}}
{"Timestamp":"2020-03-17T15:14:03.5807310-03:00","Level":"Error","MessageTemplate":"failure inside TCP socket: {message} - socket error found {socketErrorCode}","Exception":"System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_1(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.TcpSocketWriter.<>c__DisplayClass9_0.<<-ctor>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.ExponentialBackoffTcpReconnectionPolicy.ConnectAsync(Func`2 connect, Uri host, CancellationToken cancellationToken)","Properties":{"message":"No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600","socketErrorCode":"ConnectionRefused"}}
{"Timestamp":"2020-03-17T15:44:47.9292853-03:00","Level":"Information","MessageTemplate":"Starting web host"}
{"Timestamp":"2020-03-17T15:44:48.8400079-03:00","Level":"Debug","MessageTemplate":"Attempting to connect to TCP endpoint {host} after delay of {delay} seconds","Properties":{"host":"tls://localhost:5600/","delay":1}}
{"Timestamp":"2020-03-17T15:44:52.8587852-03:00","Level":"Error","MessageTemplate":"failure inside TCP socket: {message} - socket error found {socketErrorCode}","Exception":"System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_1(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.TcpSocketWriter.<>c__DisplayClass9_0.<<-ctor>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Serilog.Sinks.Network.Sinks.TCP.ExponentialBackoffTcpReconnectionPolicy.ConnectAsync(Func`2 connect, Uri host, CancellationToken cancellationToken)","Properties":{"message":"No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:5600","socketErrorCode":"ConnectionRefused"}}
